blueprints/Blueprints.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from models import User, Nikah, Payment,Madrasah, Clashed
import sqlite3

bp = Blueprint('forms', __name__)

#Home Page
@bp.route('/')
def home_page():
    return render_template("pages/home_page.html")

#Route to the Nikah Page
@bp.route('/nikah')
def nikah_page():
    return render_template("pages/nikah_page.html")

#Route to the Madrasah Page
@bp.route('/madrasah')
def madrasah_page():
    return render_template("pages/madrasah_page.html")

# Route to the Nikah Form 
@bp.route("/nikahbooking")
def nikah_booking():
    return render_template("forms/nikah_form.html")

#Route to the Madrasah Form
@bp.route("/madrasahbooking")
def madrasah_booking():
    return render_template("forms/madrasah_form.html")

#Development needed
@bp.route("/verification", methods = ['POST'])
def verification():
    print("Working pls?")
    return render_template("pages/home_page.html")

#Process for Nikah Table which retrieves the input from the nikah_form.
@bp.route("/process-nikah", methods=['GET','POST'])
def addnikah():
    if request.method == 'POST':        
        time = request.form["time"]
        date = request.form["date"]
        #checking for any bookings that could clash using the class Clashed
        if Clashed.clashed(time, date):
            flash(f'Unfortunately this booking on {date} at {time} is unavailable. Please re-book for another time/date.', 'error')
            return redirect(url_for('forms.addnikah'))
        else:
            #requesting data from the nikah_form             
            first_name = request.form["first_name"]
            last_name = request.form["last_name"]
            groom_first_name = request.form["groom_first_name"]               
            groom_last_name = request.form["groom_last_name"]               
            bride_first_name = request.form["bride_first_name"]               
            bride_last_name = request.form["bride_last_name"]               
            email = request.form["email"]                
            phone_number = request.form["phone_number"]               
            date_of_birth = request.form["date_of_birth"]               
            post_code = request.form["post_code"]            
            address_line = request.form["address_line"]             
            payment_method = request.form.get('payment_method')            
            cvc = request.form["CVC"]
            price = 130
            print(f'this is the values: {groom_first_name}, {groom_last_name}, {bride_first_name}, {bride_last_name}')
            #using the class User to store the data for the User Table
            new_user = User(first_name = first_name, last_name= last_name, email = email, phone_number= phone_number, date_of_birth= date_of_birth )
            new_user.add()
            
            #retrieving the correct coressponding UserID 
            connection = sqlite3.connect('test2.db')
            cursor = connection.cursor()
            cursor.execute('SELECT seq FROM sqlite_sequence WHERE name="User"')
            result = cursor.fetchone()
            user_id = result[0]
            connection.commit()
            cursor.close()
            
            #calling the class Nikah to store the data for the Nikah Table
            new_nikah = Nikah(user_id= user_id,groom_first_name= groom_first_name , groom_last_name= groom_last_name , bride_first_name=bride_first_name , bride_last_name=bride_last_name ,time= time, date= date, post_code= post_code, address_line= address_line)
            new_nikah.add()  
            
            #calling the class Payment to store the data for the Payment Table
            new_payment = Payment(user_id= user_id, post_code= post_code, address_line= address_line, CVC= cvc, payment_method= payment_method, price = price)
            new_payment.add()
                
            return render_template("success.html")
    else:
        return redirect(url_for('forms.addnikah'))


#Process for Madrasah Table which retrieves the user input from the madrasah_form
@bp.route("/process-madrasah", methods=['GET','POST'])
def addmadrasah():
    if request.method == 'POST':        
        time = request.form["time"]
        date = request.form["date"]
        #checking for any bookings that could clash
        print(f'the result is : {Clashed.clashed(time,date)}')

        if Clashed.clashed(time, date):
            flash(f'Unfortunately this booking on {date} at {time} is unavailable. Please re-book for another time/date.', 'clashed')
            return redirect(url_for('forms.addmadrasah'))
        
        else:
            #requesting data from the madrasah_form             
            first_name = request.form["first_name"]
            last_name = request.form["last_name"]               
            email = request.form["email"]                
            phone_number = request.form["phone_number"]
            date_of_birth = request.form["date_of_birth"]               
            child_fname = request.form["child_fname"]
            child_lname = request.form["child_lname"]
            child_date_of_birth = request.form["child_date_of_birth"]               


            #calling the class User and storign the data for the User Table
            new_user = User(first_name = first_name, last_name= last_name, email = email, phone_number= phone_number, date_of_birth= date_of_birth)
            new_user.add()
            #retrieving the correct coressponding UserID 
            connection = sqlite3.connect('test2.db')
            cursor = connection.cursor()
            cursor.execute('SELECT seq FROM sqlite_sequence WHERE name="User"')
            result = cursor.fetchone()
            user_id = result[0]
            connection.commit()
            cursor.close()
            
            #calling the class Madrasah and storing the data for the Madrasah Table 
            new_madrasah = Madrasah(user_id= user_id, time= time, date= date, child_fname = child_fname , child_lname = child_lname ,child_date_of_birth= child_date_of_birth )
            new_madrasah.add()  
                
            return render_template("success.html")
    else:
        return redirect(url_for('forms.addmadrasah'))    

blueprints/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, session, flash
from models import User, Nikah, Madrasah,Tours,Functions,Payment, Clashed, Email, Hash, Validation, DatabaseError, ServerError, UnboundLocalErrors, SocketError
import sqlite3
import json
import random
import re
#------------------------------


bp = Blueprint('routes', __name__)

#Route to the Home Page
@bp.route('/')
def index():
    return render_template("pages/index.html")

#Route to the About Us Page
@bp.route('/about-us')
def aboutus():
    return render_template("pages/aboutus.html")


#Route to the FAQ Page
@bp.route('/faq')
def faq():
    return render_template("pages/faq.html")

#Route to the Nikah Page
@bp.route('/prayer-timetable')
def prayertime():
    return render_template("pages/prayertime.html")

#Route to the Nikah Page
@bp.route('/nikah', methods = ['GET','POST'])
def nikah():
    try:
        #when the user decides to filters the graph for 1 year.
        if request.method == "POST": 
            filter = request.form.get('filter')
             # a dictionary of months and the number of bookings ,all set to 0, is created.
            months = {'01':0,
                    '02':0,
                    '03':0,
                    '04':0,
                    '05':0,
                    '06':0,
                    '07':0,
                    '08':0,
                    '09':0,
                    '10':0,
                    '11':0,
                    '12':0,
                    }              
            if filter != 'Yearly':     
            #counts the number of bookings made according to the year and orders by months    
                with sqlite3.connect('database.db') as con: 
                    cur = con.cursor()
                    cur.execute(f""" 
                        SELECT strftime('%m', Date) AS Month, COUNT(NikahID) AS NumberOfBookings
                        FROM User
                        INNER JOIN Nikah ON User.UserID = Nikah.UserID
                        INNER JOIN Hash ON User.UserID = Hash.UserID
                        WHERE strftime('%Y', Date) IN ('{filter}')
                        GROUP BY strftime('%m', Date)
                        ORDER BY Month """)
                    result = cur.fetchall()
            
                number_of_bookings = []
                #updating the dictionary so that the number of bookings correlates to the month
                for month in months: 
                    for row in result:
                        months[row[0]] = row[1] 

                for key,value in months.items():
                    number_of_bookings.append(value)

                labels = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
                return render_template("pages/nikah.html",option = filter ,number_of_bookings=json.dumps(number_of_bookings), labels=json.dumps(labels)) #returning to chart.js the labels for the x-axis and the number of bookings for the y-axis.      
            #when the user decides to filters the graph for both years.
            else: 
                #counts the number of bookings made according to the year and orders by year.
                with sqlite3.connect('database.db') as con:
                    cur = con.cursor()
                    cur.execute(f""" 
                        SELECT strftime('%Y', Date) AS Year, COUNT(NikahID) AS NumberOfBookings
                        FROM User
                        INNER JOIN Nikah ON User.UserID = Nikah.UserID
                        INNER JOIN Hash ON User.UserID = Hash.UserID
                        WHERE strftime('%Y', Date) IN ('2025','2026')
                        GROUP BY strftime('%Y', Date)
                        ORDER BY Year """)
                    result = cur.fetchall()
                # doesn't require a dictionary since we will only end up with 2 values.                    
                number_of_bookings = [x[1] for x in result]
                labels = ['2025', '2026']
                return render_template("pages/nikah.html",option = 'Total Yearly', number_of_bookings=json.dumps(number_of_bookings), labels=json.dumps(labels)) #returning to chart.js the labels for the x-axis and the number of bookings for the y-axis.



        else: #the page is just being rendered and so we will by default have the graph show both years.
            with sqlite3.connect('database.db') as con:
                cur = con.cursor()
                cur.execute(f""" 
                    SELECT strftime('%Y', Date) AS Year, COUNT(NikahID) AS NumberOfBookings
                    FROM User
                    INNER JOIN Nikah ON User.UserID = Nikah.UserID
                    INNER JOIN Hash ON User.UserID = Hash.UserID
                    WHERE strftime('%Y', Date) IN ('2025','2026')
                    GROUP BY strftime('%Y', Date)
                    ORDER BY Year """)
                result = cur.fetchall()
            number_of_bookings = [x[1] for x in result]
            labels = ['2025', '2026']
            return render_template("pages/nikah.html",option = 'Total Yearly', number_of_bookings=json.dumps(number_of_bookings), labels=json.dumps(labels))
        
    except Exception as e:
            return render_template("pages/error.html", errormsg = f'{e}')         

#Route to the Madrasah Page
@bp.route('/madrasah', methods = ['GET','POST'])
def madrasah():
    try:
        if request.method == "POST":
            months = {'01':0,
                    '02':0,
                    '03':0,
                    '04':0,
                    '05':0,
                    '06':0,
                    '07':0,
                    '08':0,
                    '09':0,
                    '10':0,
                    '11':0,
                    '12':0,
                    }                
            filter = request.form.get('filter')  
            if filter != 'Yearly':     
                with sqlite3.connect('database.db') as con:
                    cur = con.cursor()
                    cur.execute(f""" 
                        SELECT strftime('%m', Date) AS Month, COUNT(MadrasahID) AS NumberOfBookings
                        FROM User
                        INNER JOIN Madrasah ON User.UserID = Madrasah.UserID
                        INNER JOIN Hash ON User.UserID = Hash.UserID
                        WHERE strftime('%Y', Date) IN ('{filter}')
                        GROUP BY strftime('%m', Date)
                        ORDER BY Month """)
                    result = cur.fetchall()
                number_of_bookings = []

                for month in months:
                    for row in result:
                        months[row[0]] = row[1]

                for key,value in months.items():
                    number_of_bookings.append(value)

                labels = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
                return render_template("pages/madrasah.html",option = filter, number_of_bookings=json.dumps(number_of_bookings), labels=json.dumps(labels))       

            else: 
                with sqlite3.connect('database.db') as con:
                    cur = con.cursor()
                    cur.execute(f""" 
                        SELECT strftime('%Y', Date) AS Year, COUNT(MadrasahID) AS NumberOfBookings
                        FROM User
                        INNER JOIN Madrasah ON User.UserID = Madrasah.UserID
                        INNER JOIN Hash ON User.UserID = Hash.UserID
                        WHERE strftime('%Y', Date) IN ('2025','2026')
                        GROUP BY strftime('%Y', Date)
                        ORDER BY Year """)
                    result = cur.fetchall()
                number_of_bookings = [x[1] for x in result]
                labels = ['2025', '2026']
                return render_template("pages/madrasah.html",option = 'Total Yearly', number_of_bookings=json.dumps(number_of_bookings), labels=json.dumps(labels)) 



        else:
            with sqlite3.connect('database.db') as con:
                cur = con.cursor()
                cur.execute(f""" 
                    SELECT strftime('%Y', Date) AS Year, COUNT(MadrasahID) AS NumberOfBookings
                    FROM User
                    INNER JOIN Madrasah ON User.UserID = Madrasah.UserID
                    INNER JOIN Hash ON User.UserID = Hash.UserID
                    WHERE strftime('%Y', Date) IN ('2025','2026')
                    GROUP BY strftime('%Y', Date)
                    ORDER BY Year """)
                result = cur.fetchall()
            number_of_bookings = [x[1] for x in result]
            labels = ['2025', '2026']
            return render_template("pages/madrasah.html",option = 'Total Yearly', number_of_bookings=json.dumps(number_of_bookings), labels=json.dumps(labels)) 
        
    except Exception as e:
            return render_template("pages/error.html", errormsg = f'{e}')         

#Route to the Tours Page
@bp.route('/tour', methods = ['GET','POST'])
def tour():
    try:
        if request.method == "POST":
            months = {'01':0,
                    '02':0,
                    '03':0,
                    '04':0,
                    '05':0,
                    '06':0,
                    '07':0,
                    '08':0,
                    '09':0,
                    '10':0,
                    '11':0,
                    '12':0,
                    }                
            filter = request.form.get('filter')  
            if filter != 'Yearly':     
                with sqlite3.connect('database.db') as con:
                    cur = con.cursor()
                    cur.execute(f""" 
                        SELECT strftime('%m', Date) AS Month, COUNT(TourID) AS NumberOfBookings
                        FROM User

templates/pages/aboutus.html
{% extends "pages/base_page.html" %}
{% block title %} About Us {% endblock %}
{% block head %} About Al-Ansar Mosque {% endblock %}
{% block content %}
<div class="aboutus-message">
    <h2>Our Mission</h2>
    <p> Here at Al-Ansar, we strive to build a sense of unity within the local community by providing prayer and ablution faciclities to the brothers and sisters, a madrasah to children and having open arms to the public who can visit us at any time. </p>

    <h2> Join Us </h2>
    <p>We invite you in joinig us and supporting our cause. Currently, we are trying to expand and rennovate the mosque area and so we kindly ask for donations to help our project. </p>
    <hr>
    <h2> Bank Details </h2>
    <p> Masjid Maintenance & Development: <br>A/C Name: SRI LANKAN MUSLIM FOUNDATION <br>A/C: 73723801     S/C:20-49-17 </p>
    <br><br>
    <p> Funeral Account: <br>A/C Name: SRI LANKAN MUSLIM FOUNDATION <br>A/C: 70016373 S/C:20-49-17 </p>

</div>
{%endblock%}

templates/pages/aboutus_page.html
{% extends "pages/base_page.html" %}
{% block title %} About Us {% endblock %}
{% block head %} About Masjid Al-Ansar {% endblock %}
{% block content %}
<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vel nunc magna. Donec augue dui, molestie eu finibus id, euismod sed lacus. Nullam quis scelerisque nulla. Curabitur elementum ac mi ac efficitur. Quisque elementum urna diam, consequat semper tortor ullamcorper a. Nulla facilisi. Proin non lacus vel velit blandit porta rutrum vitae purus. Phasellus a nunc at nisi porta volutpat. Quisque tincidunt dui eu dui pharetra posuere. Nunc id libero ultricies, faucibus tellus vitae, efficitur mi. Nunc sit amet metus lacinia, tempus ipsum eget, efficitur libero. Proin accumsan risus vitae gravida sodales. Nullam malesuada, velit sed lacinia semper, erat arcu semper tellus, ac viverra nunc turpis at enim. Fusce vehicula augue metus, nec fermentum metus commodo eget. Sed tortor enim, consequat non tempus quis, pulvinar vitae ligula. Duis hendrerit vulputate felis quis porttitor. 
   </p>
   <p>

    it works
   Phasellus ornare sit amet nulla non posuere. Maecenas sodales ante rhoncus varius faucibus. Duis elit felis, ullamcorper mattis dolor sit amet, vulputate sollicitudin ipsum. Vivamus venenatis mollis leo, a tempus lectus aliquam a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis porta diam, et porttitor sem viverra a. Vivamus vestibulum porttitor turpis at consectetur.
   </p>

{%endblock%}

templates/pages/base_page.html
<!DOCTYPE html>
<html>
    
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
     
       <title>{%block title%}{%endblock%}</title> 
       <link rel="icon" type="image/jpg" href="{{ url_for('static', filename='icon.jpg') }}">
       <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
        {%block scripts %}{%endblock%}
    
    </head>
    
    <body style="background-color: rgb(222, 211, 184);">
        <nav class="navbar">
            <ul>
                <li> <a href="{{ url_for('routes.index') }}"> Home</a> </li>
                <li>
                    <a href="/"> Menu </a>
                    <ul class="dropdown">
                        <li> <a href="{{ url_for('routes.prayertime') }}" > Prayer Timetable </a></li>
                        <li> <a href="{{ url_for('routes.nikah') }}" > Nikah </a></li>
                        <li> <a href="{{ url_for('routes.madrasah') }}" > Madrasah </a></li>
                        <li> <a href="{{ url_for('routes.functions') }}" > Functions </a></li>
                        <li> <a href="{{ url_for('routes.tour') }}" > Tour </a></li>
                        <li> <a href="{{ url_for('routes.aboutus') }}" > About Us </a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <h1>{%block head %}{%endblock%}</h1>

        </div>

        
        {%block content%}{%endblock%}


        {%block graph%}{%endblock%}
        <hr>

        <div class="contact-message">
            <p>Address: 39 Edgehill Rd, Leicester LE4 9EA</p>
            <p>Phone: 07900 800494</p>
            <p><strong>Charity number: 1137869</strong></p>
        </div>

        <hr>
        <footer style="text-align: center;"> Al Ansar Mosque Website </footer>
    </body>

</html>

templates/pages/error.html
{% extends "pages/base_page.html" %}
{% block title %} Error Page {% endblock %}
{% block head %} Error Detected {% endblock %}
{% block content %}
<p>{{ errormsg }}</p>
<p> We are sorry that you ran into this problem. Please contact the mosque and report this issue.</p>
<a href="/">Go to Homepage</a>
{% endblock %}

templates/pages/faq_page.html
{% extends "pages/base_page.html" %}
{% block title %} FAQ {% endblock %}
{% block head %} FAQ Masjid Al-Ansar {% endblock %}
{% block content %}
<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vel nunc magna. Donec augue dui, molestie eu finibus id, euismod sed lacus. Nullam quis scelerisque nulla. Curabitur elementum ac mi ac efficitur. Quisque elementum urna diam, consequat semper tortor ullamcorper a. Nulla facilisi. Proin non lacus vel velit blandit porta rutrum vitae purus. Phasellus a nunc at nisi porta volutpat. Quisque tincidunt dui eu dui pharetra posuere. Nunc id libero ultricies, faucibus tellus vitae, efficitur mi. Nunc sit amet metus lacinia, tempus ipsum eget, efficitur libero. Proin accumsan risus vitae gravida sodales. Nullam malesuada, velit sed lacinia semper, erat arcu semper tellus, ac viverra nunc turpis at enim. Fusce vehicula augue metus, nec fermentum metus commodo eget. Sed tortor enim, consequat non tempus quis, pulvinar vitae ligula. Duis hendrerit vulputate felis quis porttitor. 
   </p>
   <p>

    it works
   Phasellus ornare sit amet nulla non posuere. Maecenas sodales ante rhoncus varius faucibus. Duis elit felis, ullamcorper mattis dolor sit amet, vulputate sollicitudin ipsum. Vivamus venenatis mollis leo, a tempus lectus aliquam a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis porta diam, et porttitor sem viverra a. Vivamus vestibulum porttitor turpis at consectetur.
   </p>

{%endblock%}

templates/pages/madrasah.html
{% extends "pages/base_page.html" %}
{% block scripts %} <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> {% endblock %}
{% block title %} Madrasah {% endblock %}
{% block head %} Madrasah at Al-Ansar Mosque {% endblock %}
{% block content %}
<div class="madrasah-message">
    <h2> What is a Madrasah? </h2>
    <p> A madrasah is the Islamic classes that aim to teach Islamic beliefs. </p><br>

    <h3> Our Madrasah </h3>
    <p> Currently our madrasah teaches both boys and girls between 10-18, the following courses: </p><br>
    <li> Hifdh Class </li>
    <li> Aadab Class </li> <br>

    <h3> Erollement </h3>
    <p> If you wish to enrol your child/children then please complete a form for each child. You will then have an appointment with the madrasah teacher to determine if the class is suitable for your child or if you need to raise any concerns with us about the madrasah or your child. A link will be sent regarding your appointment and will also allow you to edit/delete the appointment. </p>
    <p>The below bar chart shows you how many madrasah appointments have been made so far. Please understand that sometimes it can become very busy when making an apppointment. </p>
    <p>If you appointment is successful, we will send you a link about your booking in which you can then decide to edit or delete the booking.</p>

</div>
<a href="{{ url_for('routes.madrasah_booking') }}"> <button>Enrol Your Child Now</button> </a>  
<br> <hr>
{%endblock%}
{% block graph %}
<form id="filter" action="{{ url_for('routes.madrasah') }}" method="POST">
    <br>Choose a filter:     <select id="filter" name="filter">
        <option value="{{ option }}"> {{ option }} </option>
        <option value="Yearly"> Total Yearly </option>
        <option value="2025">2025</option>
        <option value="2026">2026</option>
    </select>
    <br><br><button type="submit" id="filter">Submit</button>
</form>

<!-- Wrap the canvas in a centered container -->
<div class="graph-container">
    <canvas id="myChart"></canvas>
</div>

<script>
    let number_of_bookings = JSON.parse({{ number_of_bookings | tojson }});
    let labels = JSON.parse({{ labels | tojson }});
    const ctx = document.getElementById('myChart').getContext('2d');
    let number_of_bookings_chart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: 'Number of Madrasah Bookings',
                data: number_of_bookings,
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                beginAtZero: true,
                ticks: {
                    stepSize: 1, 
                    callback: function(value) {
                        if (Number.isInteger(value)) {
                            return value;
                        }
                    }
                }
                                    
                }
            },
            responsive: true, // Make the chart responsive
            maintainAspectRatio: false // Allow the chart to adjust its aspect ratio
        }
    });
</script>
{% endblock %}

templates/pages/madrasah_page.html
{% extends "pages/base_page.html" %}
{% block title %} Madrasah {% endblock %}
{% block head %} Madrasah at Masjid Al-Ansar {% endblock %}
{% block content %}
    <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vel nunc magna. Donec augue dui, molestie eu finibus id, euismod sed lacus. Nullam quis scelerisque nulla. Curabitur elementum ac mi ac efficitur. Quisque elementum urna diam, consequat semper tortor ullamcorper a. Nulla facilisi. Proin non lacus vel velit blandit porta rutrum vitae purus. Phasellus a nunc at nisi porta volutpat. Quisque tincidunt dui eu dui pharetra posuere. Nunc id libero ultricies, faucibus tellus vitae, efficitur mi. Nunc sit amet metus lacinia, tempus ipsum eget, efficitur libero. Proin accumsan risus vitae gravida sodales. Nullam malesuada, velit sed lacinia semper, erat arcu semper tellus, ac viverra nunc turpis at enim. Fusce vehicula augue metus, nec fermentum metus commodo eget. Sed tortor enim, consequat non tempus quis, pulvinar vitae ligula. Duis hendrerit vulputate felis quis porttitor. 
   </p>
   <p>
   Phasellus ornare sit amet nulla non posuere. Maecenas sodales ante rhoncus varius faucibus. Duis elit felis, ullamcorper mattis dolor sit amet, vulputate sollicitudin ipsum. Vivamus venenatis mollis leo, a tempus lectus aliquam a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis porta diam, et porttitor sem viverra a. Vivamus vestibulum porttitor turpis at consectetur.
   </p>
   <hr>
   <a href="http://127.0.0.1:5000/madrasahbooking">
       <button>Book Madrasah Now</button>
    </a>
{%endblock%}

templates/pages/prayertime.html
{% extends "pages/base_page.html" %}
{% block title %}  Prayer Times {% endblock %}
{% block head %} Prayer Timetable{% endblock %}
{% block content %}
<p>Click below to download the month's timetable</p>
<a href="{{ url_for('static', filename='TimeTable.pdf') }}" download="PrayerTimeTable.pdf"> <button type="submit">Download Prayer Timetable</button></a>

<br>

<img src="{{ url_for('static', filename='Timetable.png') }}" height="800" width="1525">

{%endblock%}

templates/pages/prayertime_page.html
<h1> Work in Progress </h1>

templates/pages/success.html
{% extends "pages/base_page.html" %}
{% block title %} Success {% endblock %}
{% block head %} Success Page{% endblock %}
{% block content %}
<h1> Process was a Sucess!!!</h1>

<p> Please feel free to return to the homepage. </p>
<a href="/">Go to Homepage</a>
{% endblock %}

templates/pages/tour.html
{% extends "pages/base_page.html" %}
{% block scripts %} <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> {% endblock %}
{% block title %} Tours {% endblock %}
{% block head %} Tours at Al-Ansar Mosque {% endblock %}
{% block content %}
<div class="tour-message">
    <h2> Tour of the Mosque </h2>
    <p> Our mosque offers guided tours to those who are interested/learning about Islam.</p>
    <p> We welcome everyone of different faiths and beliefs to visit our mosque to no expense. </p>
    <p> The below chart shows the amount of tours we receive. </p>


    <h3> What to Expect? </h3>
    <p> Below are the list of matters that are discussed during the tour:</p>
    <li>Welcome briefing</li>
    <li>Guided tour of Ablution facilities</li>
    <li>Guided tour of Educational facilities</li>
    <li>Guided tour of prayer hall</li>
    <li>Explanation of your selected topics (please notify us in advance)</li>
    <li>Q &amp; A session</li>
    <li>Refreshments</li>    

    <h3> Book a Tour </h3>
    <p> If you wish to book a tour of the mosque, please complete the form below to make an appointment. This will allow us to further discuss any necessary arrangements for your tour. A link will be sent to your email, which will allow you to edit or delete your appointment. </p>   
</div>
<a href="{{ url_for('routes.tour_booking') }}"> <button>Make a Tour</button> </a>  
<br> <hr>
{%endblock%}
{% block graph %}
<form id="filter" action="{{ url_for('routes.tour') }}" method="POST">
    <br>Choose a filter:     <select id="filter" name="filter">
        <option value="{{ option }}"> {{ option }} </option>
        <option value="Yearly"> Total Yearly </option>
        <option value="2025">2025</option>
        <option value="2026">2026</option>
    </select>
    <br><br><button type="submit" id="filter">Submit</button>
</form>

<!-- Wrap the canvas in a centered container -->
<div class="graph-container">
    <canvas id="myChart"></canvas>
</div>

<script>
    let number_of_bookings = JSON.parse({{ number_of_bookings | tojson }});
    let labels = JSON.parse({{ labels | tojson }});
    const ctx = document.getElementById('myChart').getContext('2d');
    let number_of_bookings_chart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: 'Number of Tour Bookings',
                data: number_of_bookings,
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                beginAtZero: true,
                ticks: {
                    stepSize: 1, 
                    callback: function(value) {
                        if (Number.isInteger(value)) {
                            return value;
                        }
                    }
                }
                                    
                }
            },
            responsive: true, // Make the chart responsive
            maintainAspectRatio: false // Allow the chart to adjust its aspect ratio
        }
    });
</script>
{% endblock %}