blueprints/Blueprints.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from models import User, Nikah, Payment,Madrasah, Clashed
import sqlite3

bp = Blueprint('forms', __name__)

#Home Page
@bp.route('/')
def home_page():
    return render_template("pages/home_page.html")

#Route to the Nikah Page
@bp.route('/nikah')
def nikah_page():
    return render_template("pages/nikah_page.html")

#Route to the Madrasah Page
@bp.route('/madrasah')
def madrasah_page():
    return render_template("pages/madrasah_page.html")

# Route to the Nikah Form 
@bp.route("/nikahbooking")
def nikah_booking():
    return render_template("forms/nikah_form.html")

#Route to the Madrasah Form
@bp.route("/madrasahbooking")
def madrasah_booking():
    return render_template("forms/madrasah_form.html")

#Development needed
@bp.route("/verification", methods = ['POST'])
def verification():
    print("Working pls?")
    return render_template("pages/home_page.html")

#Process for Nikah Table which retrieves the input from the nikah_form.
@bp.route("/process-nikah", methods=['GET','POST'])
def addnikah():
    if request.method == 'POST':        
        time = request.form["time"]
        date = request.form["date"]
        #checking for any bookings that could clash using the class Clashed
        if Clashed.clashed(time, date):
            flash(f'Unfortunately this booking on {date} at {time} is unavailable. Please re-book for another time/date.', 'error')
            return redirect(url_for('forms.addnikah'))
        else:
            #requesting data from the nikah_form             
            first_name = request.form["first_name"]
            last_name = request.form["last_name"]
            groom_first_name = request.form["groom_first_name"]               
            groom_last_name = request.form["groom_last_name"]               
            bride_first_name = request.form["bride_first_name"]               
            bride_last_name = request.form["bride_last_name"]               
            email = request.form["email"]                
            phone_number = request.form["phone_number"]               
            date_of_birth = request.form["date_of_birth"]               
            post_code = request.form["post_code"]            
            address_line = request.form["address_line"]             
            payment_method = request.form.get('payment_method')            
            cvc = request.form["CVC"]
            price = 130
            print(f'this is the values: {groom_first_name}, {groom_last_name}, {bride_first_name}, {bride_last_name}')
            #using the class User to store the data for the User Table
            new_user = User(first_name = first_name, last_name= last_name, email = email, phone_number= phone_number, date_of_birth= date_of_birth )
            new_user.add()
            
            #retrieving the correct coressponding UserID 
            connection = sqlite3.connect('test2.db')
            cursor = connection.cursor()
            cursor.execute('SELECT seq FROM sqlite_sequence WHERE name="User"')
            result = cursor.fetchone()
            user_id = result[0]
            connection.commit()
            cursor.close()
            
            #calling the class Nikah to store the data for the Nikah Table
            new_nikah = Nikah(user_id= user_id,groom_first_name= groom_first_name , groom_last_name= groom_last_name , bride_first_name=bride_first_name , bride_last_name=bride_last_name ,time= time, date= date, post_code= post_code, address_line= address_line)
            new_nikah.add()  
            
            #calling the class Payment to store the data for the Payment Table
            new_payment = Payment(user_id= user_id, post_code= post_code, address_line= address_line, CVC= cvc, payment_method= payment_method, price = price)
            new_payment.add()
                
            return render_template("success.html")
    else:
        return redirect(url_for('forms.addnikah'))


#Process for Madrasah Table which retrieves the user input from the madrasah_form
@bp.route("/process-madrasah", methods=['GET','POST'])
def addmadrasah():
    if request.method == 'POST':        
        time = request.form["time"]
        date = request.form["date"]
        #checking for any bookings that could clash
        print(f'the result is : {Clashed.clashed(time,date)}')

        if Clashed.clashed(time, date):
            flash(f'Unfortunately this booking on {date} at {time} is unavailable. Please re-book for another time/date.', 'clashed')
            return redirect(url_for('forms.addmadrasah'))
        
        else:
            #requesting data from the madrasah_form             
            first_name = request.form["first_name"]
            last_name = request.form["last_name"]               
            email = request.form["email"]                
            phone_number = request.form["phone_number"]
            date_of_birth = request.form["date_of_birth"]               
            child_fname = request.form["child_fname"]
            child_lname = request.form["child_lname"]
            child_date_of_birth = request.form["child_date_of_birth"]               


            #calling the class User and storign the data for the User Table
            new_user = User(first_name = first_name, last_name= last_name, email = email, phone_number= phone_number, date_of_birth= date_of_birth)
            new_user.add()
            #retrieving the correct coressponding UserID 
            connection = sqlite3.connect('test2.db')
            cursor = connection.cursor()
            cursor.execute('SELECT seq FROM sqlite_sequence WHERE name="User"')
            result = cursor.fetchone()
            user_id = result[0]
            connection.commit()
            cursor.close()
            
            #calling the class Madrasah and storing the data for the Madrasah Table 
            new_madrasah = Madrasah(user_id= user_id, time= time, date= date, child_fname = child_fname , child_lname = child_lname ,child_date_of_birth= child_date_of_birth )
            new_madrasah.add()  
                
            return render_template("success.html")
    else:
        return redirect(url_for('forms.addmadrasah'))    

blueprints/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, session, flash
from models import User, Nikah, Madrasah,Tours,Functions,Payment, Clashed, Email, Hash, Validation, DatabaseError, ServerError, UnboundLocalErrors, SocketError
import sqlite3
import json
import random
import re
#------------------------------


bp = Blueprint('routes', __name__)

#Route to the Home Page
@bp.route('/')
def index():
    return render_template("pages/index.html")

#Route to the About Us Page
@bp.route('/about-us')
def aboutus():
    return render_template("pages/aboutus.html")


#Route to the FAQ Page
@bp.route('/faq')
def faq():
    return render_template("pages/faq.html")

#Route to the Nikah Page
@bp.route('/prayer-timetable')
def prayertime():
    return render_template("pages/prayertime.html")

#Route to the Nikah Page
@bp.route('/nikah', methods = ['GET','POST'])
def nikah():
    try:
        #when the user decides to filters the graph for 1 year.
        if request.method == "POST": 
            filter = request.form.get('filter')
             # a dictionary of months and the number of bookings ,all set to 0, is created.
            months = {'01':0,
                    '02':0,
                    '03':0,
                    '04':0,
                    '05':0,
                    '06':0,
                    '07':0,
                    '08':0,
                    '09':0,
                    '10':0,
                    '11':0,
                    '12':0,
                    }              
            if filter != 'Yearly':     
            #counts the number of bookings made according to the year and orders by months    
                with sqlite3.connect('database.db') as con: 
                    cur = con.cursor()
                    cur.execute(f""" 
                        SELECT strftime('%m', Date) AS Month, COUNT(NikahID) AS NumberOfBookings
                        FROM User
                        INNER JOIN Nikah ON User.UserID = Nikah.UserID
                        INNER JOIN Hash ON User.UserID = Hash.UserID
                        WHERE strftime('%Y', Date) IN ('{filter}')
                        GROUP BY strftime('%m', Date)
                        ORDER BY Month """)
                    result = cur.fetchall()
            
                number_of_bookings = []
                #updating the dictionary so that the number of bookings correlates to the month
                for month in months: 
                    for row in result:
                        months[row[0]] = row[1] 

                for key,value in months.items():
                    number_of_bookings.append(value)

                labels = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
                return render_template("pages/nikah.html",option = filter ,number_of_bookings=json.dumps(number_of_bookings), labels=json.dumps(labels)) #returning to chart.js the labels for the x-axis and the number of bookings for the y-axis.      
            #when the user decides to filters the graph for both years.
            else: 
                #counts the number of bookings made according to the year and orders by year.
                with sqlite3.connect('database.db') as con:
                    cur = con.cursor()
                    cur.execute(f""" 
                        SELECT strftime('%Y', Date) AS Year, COUNT(NikahID) AS NumberOfBookings
                        FROM User
                        INNER JOIN Nikah ON User.UserID = Nikah.UserID
                        INNER JOIN Hash ON User.UserID = Hash.UserID
                        WHERE strftime('%Y', Date) IN ('2025','2026')
                        GROUP BY strftime('%Y', Date)
                        ORDER BY Year """)
                    result = cur.fetchall()
                # doesn't require a dictionary since we will only end up with 2 values.                    
                number_of_bookings = [x[1] for x in result]
                labels = ['2025', '2026']
                return render_template("pages/nikah.html",option = 'Total Yearly', number_of_bookings=json.dumps(number_of_bookings), labels=json.dumps(labels)) #returning to chart.js the labels for the x-axis and the number of bookings for the y-axis.



        else: #the page is just being rendered and so we will by default have the graph show both years.
            with sqlite3.connect('database.db') as con:
                cur = con.cursor()
                cur.execute(f""" 
                    SELECT strftime('%Y', Date) AS Year, COUNT(NikahID) AS NumberOfBookings
                    FROM User
                    INNER JOIN Nikah ON User.UserID = Nikah.UserID
                    INNER JOIN Hash ON User.UserID = Hash.UserID
                    WHERE strftime('%Y', Date) IN ('2025','2026')
                    GROUP BY strftime('%Y', Date)
                    ORDER BY Year """)
                result = cur.fetchall()
            number_of_bookings = [x[1] for x in result]
            labels = ['2025', '2026']
            return render_template("pages/nikah.html",option = 'Total Yearly', number_of_bookings=json.dumps(number_of_bookings), labels=json.dumps(labels))
        
    except Exception as e:
            return render_template("pages/error.html", errormsg = f'{e}')         

#Route to the Madrasah Page
@bp.route('/madrasah', methods = ['GET','POST'])
def madrasah():
    try:
        if request.method == "POST":
            months = {'01':0,
                    '02':0,
                    '03':0,
                    '04':0,
                    '05':0,
                    '06':0,
                    '07':0,
                    '08':0,
                    '09':0,
                    '10':0,
                    '11':0,
                    '12':0,
                    }                
            filter = request.form.get('filter')  
            if filter != 'Yearly':     
                with sqlite3.connect('database.db') as con:
                    cur = con.cursor()
                    cur.execute(f""" 
                        SELECT strftime('%m', Date) AS Month, COUNT(MadrasahID) AS NumberOfBookings
                        FROM User
                        INNER JOIN Madrasah ON User.UserID = Madrasah.UserID
                        INNER JOIN Hash ON User.UserID = Hash.UserID
                        WHERE strftime('%Y', Date) IN ('{filter}')
                        GROUP BY strftime('%m', Date)
                        ORDER BY Month """)
                    result = cur.fetchall()
                number_of_bookings = []

                for month in months:
                    for row in result:
                        months[row[0]] = row[1]

                for key,value in months.items():
                    number_of_bookings.append(value)

                labels = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
                return render_template("pages/madrasah.html",option = filter, number_of_bookings=json.dumps(number_of_bookings), labels=json.dumps(labels))       

            else: 
                with sqlite3.connect('database.db') as con:
                    cur = con.cursor()
                    cur.execute(f""" 
                        SELECT strftime('%Y', Date) AS Year, COUNT(MadrasahID) AS NumberOfBookings
                        FROM User
                        INNER JOIN Madrasah ON User.UserID = Madrasah.UserID
                        INNER JOIN Hash ON User.UserID = Hash.UserID
                        WHERE strftime('%Y', Date) IN ('2025','2026')
                        GROUP BY strftime('%Y', Date)
                        ORDER BY Year """)
                    result = cur.fetchall()
                number_of_bookings = [x[1] for x in result]
                labels = ['2025', '2026']
                return render_template("pages/madrasah.html",option = 'Total Yearly', number_of_bookings=json.dumps(number_of_bookings), labels=json.dumps(labels)) 



        else:
            with sqlite3.connect('database.db') as con:
                cur = con.cursor()
                cur.execute(f""" 
                    SELECT strftime('%Y', Date) AS Year, COUNT(MadrasahID) AS NumberOfBookings
                    FROM User
                    INNER JOIN Madrasah ON User.UserID = Madrasah.UserID
                    INNER JOIN Hash ON User.UserID = Hash.UserID
                    WHERE strftime('%Y', Date) IN ('2025','2026')
                    GROUP BY strftime('%Y', Date)
                    ORDER BY Year """)
                result = cur.fetchall()
            number_of_bookings = [x[1] for x in result]
            labels = ['2025', '2026']
            return render_template("pages/madrasah.html",option = 'Total Yearly', number_of_bookings=json.dumps(number_of_bookings), labels=json.dumps(labels)) 
        
    except Exception as e:
            return render_template("pages/error.html", errormsg = f'{e}')         

#Route to the Tours Page
@bp.route('/tour', methods = ['GET','POST'])
def tour():
    try:
        if request.method == "POST":
            months = {'01':0,
                    '02':0,
                    '03':0,
                    '04':0,
                    '05':0,
                    '06':0,
                    '07':0,
                    '08':0,
                    '09':0,
                    '10':0,
                    '11':0,
                    '12':0,
                    }                
            filter = request.form.get('filter')  
            if filter != 'Yearly':     
                with sqlite3.connect('database.db') as con:
                    cur = con.cursor()
                    cur.execute(f""" 
                        SELECT strftime('%m', Date) AS Month, COUNT(TourID) AS NumberOfBookings
                        FROM User

templates/tables/base_table.html
<!DOCTYPE html>
<html>
    
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
     
       <title>{%block title%}{%endblock%}</title> 
       <link rel="icon" type="image/jpg" href="{{ url_for('static', filename='icon.jpg') }}">
       <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
        {%block scripts %}{%endblock%}
    
    </head>
    
    <body style="background-color: rgb(222, 211, 184);">
        <nav class="navbar">
            <ul>
                <li> <a href="{{ url_for('routes.index') }}"> Home</a> </li>
                <li>
                    <a href="/"> Menu </a>
                    <ul class="dropdown">
                        <li> <a href="{{ url_for('routes.prayertime') }}" > Prayer Timetable </a></li>
                        <li> <a href="{{ url_for('routes.nikah') }}" > Nikah </a></li>
                        <li> <a href="{{ url_for('routes.madrasah') }}" > Madrasah </a></li>
                        <li> <a href="{{ url_for('routes.functions') }}" > Functions </a></li>
                        <li> <a href="{{ url_for('routes.tour') }}" > Tour </a></li>
                        <li> <a href="{{ url_for('routes.aboutus') }}" > About Us </a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <h1>{%block head %}{%endblock%}</h1>

        <table border="1px">
            <thead>
                <td><strong>UserID</strong></td>
                <td><strong>First Name</strong></td>
                <td><strong>Last Name</strong></td>
                <td><strong>Email</strong></td>
                <td><strong>Phone Number</strong></td>
                <td><strong>Date of Birth</strong></td>
            </thead>
            {% for row in rows %}
            <tr>
                <td>{{ row["UserID"] }}</td>
                <td>{{ row["FirstName"]}}</td>
                <td>{{ row["LastName"] }}</td>
                <td>{{ row["Email"] }}</td>
                <td>{{ row["PhoneNumber"] }}</td>
                <td>{{ row["DoB"] }}</td>
            </tr>
            {% endfor %}
        </table> <br>
        {%block content %}{%endblock%}




        <hr>
        <footer style="text-align: center;"> Al Ansar Mosque Website </footer>
    </body>

</html>

templates/tables/function_table.html
{% extends "tables/base_table.html" %}
{% block title %} Your Function Booking {% endblock %}
{% block head %} Editing Your Function Booking {% endblock %}
{% block id %} FunctionID {% endblock %}
{% block content %}
<table border="1px">
    <thead>
        <td><strong>FunctionID</strong></td>
        <td><strong>Post Code</strong></td>
        <td><strong>Address Line</strong></td>
        <td><strong>Event Type</strong></td>
        <td><strong>Time</strong></td>
        <td><strong>Date</strong></td><br>
        <td></td>
        <td></td>
    </thead>

    {% for row in rows %}
    <tr>
        <td>{{ row["FunctionID"] }}</td>
        <td>{{ row["PostCode"] }}</td>
        <td>{{ row["AddressLine"] }}</td>
        <td>{{ row["EventType"] }}</td>
        <td>{{ row["Time"] }}</td>
        <td>{{ row["Date"] }}</td>
        <td><form action="/edit/function" method="POST"><input type="hidden" name="userid" value="{{ row['UserID'] }}"><input type="submit" value="Edit"></form> </td>
        <td><form onsubmit="return confirm('There is no gurantee that you can make this same booking again.\n Are you sure you want to DELETE this function booking?');" action="/delete/function" method="POST"><input type="hidden" name="userid" value="{{ row['UserID'] }}"><input type="submit" value="Delete"></form> </td>

    </tr>
    {% endfor %}
</table>
{%endblock%}

templates/tables/list.html
<!DOCTYPE html>
<html>
    
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, intial-scale=1"> 
     
       <title>Booking</title> 
       <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">


    
    </head>
    
    <body style="background-color: rgb(222, 211, 184);">
        <nav>
            <ul>
                <li> <a href="{{ url_for('routes.index') }}"> Home</a> </li>
                <li>
                    <a href="/"> Menu </a>
                    <ul class="dropdown">
                        <li> <a href="/nikah" > Nikah </a></li>
                        <li> <a href="/madrasah" > Madrasah </a></li>
                        <li> <a href="/service" > Service </a></li>
                        <li> <a href="/tours" > Tours </a></li>
                        <li> <a href="/about-us" > About Us </a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <h1>Your booking "{{ digest }}" </h1>

        </div>

        <hr>
        <table class="center"    border="1px">
            <thead>
                <td><strong>User ID</strong></td>
                <td><strong>First Name</strong></td>
                <td><strong>Last Name</strong></td>
                <td><strong>Email</strong></td>
                <td><strong>PhoneNumber</strong></td>
                <td><strong>DoB</strong></td>
                <td></td>
                <td></td>
            </thead>

            {% for row in rows %}
            <tr>
                <td>{{ row["UserID"] }}</td>
                <td>{{ row["FirstName"] }}</td>
                <td> {{ row["LastName"]}}</td>
                <td>{{ row["Email"] }}</td>
                <td>{{ row["PhoneNumber"] }}</td>
                <td>{{ row["DoB"] }}</td>
                <td><form action="{{url_for('routes.addnikah')}}" method="POST"><input type="hidden" name="id" value="{{ row['rowid'] }}"><input type="submit" value="Edit"></form> </td>
            </tr>
            {% endfor %}
        </table>

    
    </body>

</html>

templates/tables/madrasah_table.html
{% extends "tables/base_table.html" %}
{% block title %} Your Madrasah Booking {% endblock %}
{% block head %} Editing Your Madrasah Booking {% endblock %}
{% block id %} MadrasahID {% endblock %}
{% block content %}
<table border="1px">
    <thead>
        <td><strong>MadrasahID</strong></td>
        <td><strong>Child First Name</strong></td>
        <td><strong>Child Last Name</strong></td>
        <td><strong>Child Date of Birth</strong></td>
        <td><strong>Time</strong></td>
        <td><strong>Date</strong></td><br>
        <td></td>
        <td></td>
    </thead>

    {% for row in rows %}
    <tr>
        <td>{{ row["MadrasahID"] }}</td>
        <td>{{ row["ChildFirstName"] }}</td>
        <td>{{ row["ChildLastName"] }}</td>
        <td>{{ row["ChildDoB"] }}</td>
        <td>{{ row["Time"] }}</td>
        <td>{{ row["Date"] }}</td>
        <td><form action="/edit/madrasah" method="POST"><input type="hidden" name="userid" value="{{ row['UserID'] }}"><input type="submit" value="Edit"></form> </td>
        <td><form onsubmit="return confirm('There is no gurantee that you can make this same booking again.\n Are you sure you want to DELETE this madrasah booking?');" action="/delete/madrasah" method="POST"><input type="hidden" name="userid" value="{{ row['UserID'] }}"><input type="submit" value="Delete"></form> </td>

    </tr>
    {% endfor %}
</table>
{%endblock%}

templates/tables/nikah_table.html
{% extends "tables/base_table.html" %}
{% block title %} Your Nikah Booking {% endblock %}
{% block head %} Editing Your Nikah Booking {% endblock %}
{% block id %} NikahID {% endblock %}
{% block content %}
<table border="1px">
    <thead>
        <td><strong>NikahID</strong></td>
        <td><strong>Groom First Name</strong></td>
        <td><strong>Groom Last Name</strong></td>
        <td><strong>Bride First Name</strong></td>
        <td><strong>Bride Last Name</strong></td>
        <td><strong>Address Line</strong></td>
        <td><strong>Post Code</strong></td>
        <td><strong>Time</strong></td>
        <td><strong>Date</strong></td><br>
        <td></td>
        <td></td>
    </thead>

    {% for row in rows %}
    <tr>
        <td>{{ row["NikahID"] }}</td>        
        <td>{{ row["GroomFirstName"] }}</td>
        <td>{{ row["GroomLastName"] }}</td>
        <td>{{ row["BrideFirstName"] }}</td>
        <td>{{ row["BrideLastName"] }}</td>
        <td>{{ row["AddressLine"] }}</td>
        <td>{{ row["PostCode"] }}</td>
        <td>{{ row["Time"] }}</td>
        <td>{{ row["Date"] }}</td>
        <td><form action="/edit/nikah" method="POST"><input type="hidden" name="userid" value="{{ row['UserID'] }}"><input type="submit" value="Edit"></form> </td>
        <td><form onsubmit="return confirm('There is no gurantee that you can make this same booking again.\n Are you sure you want to DELETE this nikah booking?');" action="/delete/nikah" method="POST"><input type="hidden" name="userid" value="{{ row['UserID'] }}"><input type="submit" value="Delete"></form> </td>

    </tr>
    {% endfor %}
</table>
{%endblock%}

templates/tables/tour_table.html
{% extends "tables/base_table.html" %}
{% block title %} Your Tour Booking {% endblock %}
{% block head %} Editing Your Tour Booking {% endblock %}
{% block id %} TourID {% endblock %}
{% block content %}
<table border="1px">
    <thead>
        <td><strong>TourID</strong></td>
        <td><strong>Number Of People</strong></td>
        <td><strong>Event Type</strong></td>
        <td><strong>Time</strong></td>
        <td><strong>Date</strong></td><br>
        <td></td>
        <td></td>
    </thead>

    {% for row in rows %}
    <tr>
        <td>{{ row["TourID"] }}</td>
        <td>{{ row["NumberOfPeople"] }}</td>
        <td>{{ row["EventType"] }}</td>
        <td>{{ row["Time"] }}</td>
        <td>{{ row["Date"] }}</td>
        <td><form action="/edit/tour" method="POST"><input type="hidden" name="userid" value="{{ row['UserID'] }}"><input type="submit" value="Edit"></form> </td>
        <td><form onsubmit="return confirm('There is no gurantee that you can make this same booking again.\n Are you sure you want to DELETE this tour booking?');" action="/delete/tour" method="POST"><input type="hidden" name="userid" value="{{ row['UserID'] }}"><input type="submit" value="Delete"></form> </td>

    </tr>
    {% endfor %}
</table>
{%endblock%}